modLoader="javafml"
loaderVersion="${loader_version_range}"

issueTrackerURL="https://github.com/Harleyoc1/ChunkAnimator/issues"

license="${mod_license}"

[[mods]]

displayName="${mod_name}"
modId="${mod_id}"
version="${mod_version}"

authors="Astryxion"
credits="Astryxion, Lumien"

description='''
A small client side mod that animates the appeareance of chunks so that they don't just instantly appear.
'''

[[mixins]]
config="${mod_id}.mixins.json"

displayURL="https://www.curseforge.com/minecraft/mc-mods/chunk-animator"
updateJSONURL="https://github.com/Harleyoc1/ChunkAnimator/blob/1.21/version_info.json?raw=true"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
